version: '3'

services:
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
